
# This is a basic workflow to help you get started with Actions

name: Make PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "make-pdfs"
  make-pdf:
    name: Make PDF as release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "ms.tex"
      
      - name: Set Release Meta Info
        id: meta-info
        run: |
          set -o noglob
          NAME=`echo ${MESSAGE} | head -n 1`
          BODY=`echo ${MESSAGE} | tail -n +2`
          echo "::set-output name=NAME::$NAME"
          echo "::set-output name=BODY::$BODY"
          echo "::set-output name=DATE::$(date +"%Y-%m-%d_%H%M")"
          echo "$NAME $BODY"
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ms.pdf
          name: ${{ steps.meta-info.outputs.NAME }}
          tag_name: ${{ steps.meta-info.outputs.DATE }}
          body: ${{ steps.meta-info.outputs.BODY }}
